image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install theme for delelopment
    init: | 
      jlpm &&
      pip install . &&
      mkdir -p /home/gitpod/.pyenv/versions/3.8.13/share/jupyter/lab/settings &&
      

  - name: Run JupyterLab
    command: |
      mkdir -p /home/gitpod/.pyenv/versions/3.8.13/share/jupyter/lab/settings
      cp dev/jupyterlab_settings/overrides.json /home/gitpod/.pyenv/versions/3.8.13/share/jupyter/lab/settings/overrides.json
      cd /workspace && jupyter lab --no-browser --ip=0.0.0.0 --port=9999 --NotebookApp.token='' --NotebookApp.password=''

ports:
- name: JupyterLab
  port: 9999
  onOpen: notify


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false